// Bundles the editable JSON in /content into app/data/content.js so the app
// can load it with a plain <script> tag (works offline, even from file://).
//
// Optional authoritative files are picked up automatically when present:
//   content/black_folk_words_quote_bank_v1.json  (WORDS; else words_from_brief.json)
//   content/black_folk_knowledge_map_v1.json     (map edges; else derived in-app)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const path = (f) => join(root, 'content', f);
const read = (f) => JSON.parse(readFileSync(path(f), 'utf8'));
const optional = (f) => (existsSync(path(f)) ? read(f) : null);

const quoteBank = optional('black_folk_words_quote_bank_v1.json');
const bundle = {
  curriculum: read('black_thought_v1_revised_curriculum.json'),
  playtest: read('black_folk_v1_1_tuned_playtest.json'),
  links: read('links.json'),
  words: quoteBank || read('words_from_brief.json'),
  wordsSource: quoteBank ? 'black_folk_words_quote_bank_v1.json' : 'words_from_brief.json',
  knowledgeMap: optional('black_folk_knowledge_map_v1.json'),
};

const out = join(root, 'app', 'data', 'content.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  '// GENERATED by scripts/build-data.mjs from /content. Do not edit by hand.\n' +
    'globalThis.BF_CONTENT = ' + JSON.stringify(bundle) + ';\n'
);
console.log(`content bundled → app/data/content.js (WORDS: ${bundle.wordsSource}; map: ${bundle.knowledgeMap ? 'supplied' : 'derived'})`);
