// Bundles the editable JSON in /content into app/data/content.js so the app
// can load it with a plain <script> tag (works offline, even from file://).
//
// V1.5 sources of truth:
//   black_folk_v1_5_master_curriculum.json  50 nodes, 9 threads, 8 debates, context, deepening cards
//   black_folk_v1_5_encounter_pack.json      50 DISCOVER + 80 encounters, starter + bridge sessions
//   black_folk_v1_5_knowledge_map.json       graph edges + the verified WORDS quote bank
// Editorial layers (no new claims):
//   links.json               thread steps / debate sides wiring onto node ids
//   v1_5_interactions.json   HOW each encounter is played (binary, sort, pick, recall…)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => JSON.parse(readFileSync(join(root, 'content', f), 'utf8'));

const map = read('black_folk_v1_5_knowledge_map.json');
const bundle = {
  curriculum: read('black_folk_v1_5_master_curriculum.json'),
  playtest: read('black_folk_v1_5_encounter_pack.json'),
  knowledgeMap: map,
  links: read('links.json'),
  interactions: read('v1_5_interactions.json'),
  wordsSource: 'black_folk_v1_5_knowledge_map.json',
};

const out = join(root, 'app', 'data', 'content.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  '// GENERATED by scripts/build-data.mjs from /content. Do not edit by hand.\n' +
    'globalThis.BF_CONTENT = ' + JSON.stringify(bundle) + ';\n'
);
console.log(`content bundled → app/data/content.js (${bundle.curriculum.playable_nodes.length} nodes, ${bundle.playtest.discovery_cards.length + bundle.playtest.encounters.length} playable items)`);
