// Bundles the editable JSON in /content into app/data/content.js so the app
// can load it with a plain <script> tag (works offline, even from file://).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => JSON.parse(readFileSync(join(root, 'content', f), 'utf8'));

const bundle = {
  curriculum: read('black_thought_v1_revised_curriculum.json'),
  playtest: read('black_folk_v1_1_tuned_playtest.json'),
  links: read('links.json'),
};

const out = join(root, 'app', 'data', 'content.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  '// GENERATED by scripts/build-data.mjs from /content. Do not edit by hand.\n' +
    'globalThis.BF_CONTENT = ' + JSON.stringify(bundle) + ';\n'
);
console.log('content bundled → app/data/content.js');
